### ISSUE TITLE
There is a need to create a "fromJson" method using snippets

### ISSUE THREAD

**Issue by tkasymuulu** [Arkroot-Innovations/freezed-snippets#1]
Hello! I am using this snippet. It helps a lot with development. I would like the automatic creation of the "fromJson" method. At each creation data classes to have to be registered manually.
--------------- For Example -----------------
factory AuthModel.fromJson(Map<String, dynamic> json) => _$AuthModelFromJson(json);

**Comment by shan-shaji** [comment]
@tkasymuulu Thanks for opening the issue. Sorry for the delayed response. I will work on it this weekend.

**Comment by shan-shaji** [comment]
@tkasymuulu I have deployed `v0.0.2` with the desired feature.

**Comment by tkasymuulu** [comment]
Hi! Thanks for adding this feature!
Method fromJson you specially carried out for data class?
Although the method must be inside the data class to work properly.

**Comment by shan-shaji** [comment]
@tkasymuulu Yes it's added for the data class.
