### ISSUE TITLE
Wrong curly brace placement

### ISSUE THREAD

**Issue by joachimbulow** [Arkroot-Innovations/freezed-snippets#3]
Move down the curly brace two ticks to get no compile errors

<img width="913" alt="image" src="https://github.com/ArkrootHQ/freezed-snippets/assets/43139346/c2175cd5-a98d-441b-bb81-f94ce72c26f6">

**Comment by shan-shaji** [comment]
Hey @joachimbulow , Thanks for opening the issue. Could you please mark the issue in the screenshot for better understanding.

**Comment by joachimbulow** [comment]
Instead if using top level factory declaration, just move the line 4 curly bracket to line 7.
Maybe it is due to newer Dart version idk

**Comment by shan-shaji** [comment]
Okay thanks @joachimbulow for raising this. I will fix it.

**Comment by joachimbulow** [comment]
@shan-shaji i have opened a pr https://github.com/ArkrootHQ/freezed-snippets/pull/4
