### ISSUE TITLE
Also generate the import statements

### ISSUE THREAD

**Issue by leiflinse-trivector** [Arkroot-Innovations/freezed-snippets#5]
Thanks for the snippet plugin.

If I create a fdataclass with name `DataModel`, I would be good if it adds imports and part-imports like this:

```
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

part 'data_model.freezed.dart';
part 'data_model.g.dart';
```

**Comment by shan-shaji** [comment]
Thanks, @leiflinse-trivector for opening the issue. Would you like to try working on it? If not I will work on it during the weekend.
